### ISSUE TITLE
Alpha - Status

### ISSUE THREAD

**Issue by Tallion-07** [Tallion-07/Blender-2.8-Plug-in-Giants-Engine#41]
### Testing post-mortem
- [ ] Testing post-mortem completed #24 #39 
***
- [ ] init.py #25
- [ ] i3d_ui #29
- [ ] import_i3d #30 
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

### Speed testing
- [ ] speed test complete #24 
***
- [ ] init.py #25
- [ ] i3d_ui #29
- [ ] import_i3d #30  
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

### Function tests
- [ ]  function tests complete #24 
***
- [ ] init.py #25
- [ ] i3d_ui #29
- [ ] import_i3d #30 
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

### Checklist for Blender.org
- [ ] Completed #24 #39
- [ ] _init_.py #25 
- [ ] i3d_ui #29
- [ ] import_i3d #30 
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

***

### Debugging code
- [ ] debugging completed
***

- [ ] init.py #25
- [ ] i3d_ui #29
- [ ] import_i3d #30 
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

### Code review
- [ ] code review complete
***] init.py  #25
- [ ] i3d_ui #29
- [ ] import_i3d #30 
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34

### Code writing
- [ ] code writing completed
***
- [ ] init.py #25
  - [x] Bl info resolved #6
- [ ] i3d_ui #29
- [ ] import_i3d #30
- [ ] lib_i3d #31 
- [ ] dccBlender #32 
- [ ] export_i3d #33 
- [ ] exportIO_i3d #35 
- [ ] exportUI_i3d #34 

### Initial Issue writing
- [ ] Issuse writing completed
***
- [ ] init.py #25 
- [ ] i3d_ui #29
- [ ] import_i3d #30
- [ ] lib_i3d #31
- [ ] dccBlender #32
- [ ] export_i3d #33
- [ ] exportIO_i3d #35
- [ ] exportUI_i3d #34

**Comment by Tallion-07** [comment]
@Tallion-07

**Comment by ssnd292** [comment]
I just comment here: Are you maybe intereset in Beta Testers or a dedicated team to support you? The modding collective VertexDezign would really like to support your endeavours.

**Comment by Tallion-07** [comment]
@ssnd292 thank you for your comments and offer of support, when this project gets to the point of testing, I would appreciate that. as you can see it's a fair way off for that, but i am certainly looking forward to that day, when it hits testing.

**Comment by ssnd292** [comment]
@Tallion-07 The community appreciates your effort. If there is anything we can support the development, please, let us know.

I will post an link to the Vertexdezign Discord here for future use:
https://discord.gg/GVfNFpM

Thank you again for working on this. Blender now is a main industry tool, especially for freelancer and hobbyist. Giants blatantly ignoring it, is fatal.

**Comment by StjerneIdioten** [comment]
I am also interested in helping with this endeavor. I forked your repo a while back to have a go at it myself, without interfering with your stuff.

I have been looking through the plugin and from what I can see most of the code is either horribly outdated or just not used, at least on the blender side of things. The module responsible for exporting to xml(i3d) might still be useful. 
Therefore my course of action has been to simply start from scratch with proper package/module naming, staying true to both the blender 2.8 and python pep8 standard.

I can see from your issuetracker that you have structured it as purely an "upgrade" to the existing modules, but I do think that it is necessary to rebuild it using modern syntax and not necessary follow the same structuring as the original plugin.

I will admit that I don't know much about creating addons for blender, but I have spend the last couple of days getting up to speed and taking apart the original i3d-exporter. As well as creating a working UI for the exporter using the newer way of doing it extracted from the source-code of the stl-exporter, that is supplied by the blender foundation.

I will continue to work on this when I have the time as I am very much interested in getting a working exporter that supports some of the newer blender features (especially collections)

**Comment by ssnd292** [comment]
> I will continue to work on this when I have the time as I am very much interested in getting a working exporter that supports some of the newer blender features (especially collections)

If you need any help or other devs to work, make sure to let me know or join the Discord I posted earlier. Always eager to help!

**Comment by StjerneIdioten** [comment]
I have already joined that discord (What is it with developers and discord these days?) but I would rather like a more official channel, for this project only, like a Slack or something and of course for my fork to eventually be merged into this project to not have two disjunct projects working on the same thing.

Also you discord seems to be primarily in German? I can mostly follow what you guys are writing (Hurray for mandatory german in danish schools) but I assume you guys don't mind english either.
